### ISSUE TITLE
More info about yourself!

### ISSUE THREAD

**Issue by meganjro** [epid8060fall2019/Amanda-Introduction#1]
Hi Amanda, 

I'm impressed by that you say you do powerlifting! I've watched a few meets and I'm amazed at how strong these lifters are. What is your favorite lift? 

Also did working at the Food Research Institute change your eating or cooking habits at all based on what you studied?

Thanks!

Megan Robertson

**Comment by askarlupka** [comment]
Hey @meganjro. Do you know someone that lifts? Usually people just don't drop by to watch a meet without having someone that they know being there.
I added more information about lifting and the FRI. Thanks for reading my bio!
